/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mam_lambo_AlgoWrapper */

#ifndef _Included_com_mam_lambo_AlgoWrapper
#define _Included_com_mam_lambo_AlgoWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mam_lambo_AlgoWrapper
 * Method:    terminate
 * Signature: ()V
 */
// JNIEXPORT void JNICALL Java_com_mam_lambo_AlgoWrapper_terminate (JNIEnv *, jobject);

/*
 * Class:     com_mam_lambo_AlgoWrapper
 * Method:    execute
 * Signature: ([F)[F
 */
// JNIEXPORT jfloatArray JNICALL Java_com_mam_lambo_AlgoWrapper_execute (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     com_mam_lambo_AlgoWrapper
 * Method:    getInputDimensions
 * Signature: ()[I
 */
// JNIEXPORT jintArray JNICALL Java_com_mam_lambo_AlgoWrapper_getInputDimensions (JNIEnv *, jobject);

/*
 * Class:     com_mam_lambo_AlgoWrapper
 * Method:    init
 * Signature: (Ljava/lang/String;IZ)I
 */
// JNIEXPORT jint JNICALL Java_com_mam_lambo_AlgoWrapper_init (JNIEnv *, jobject, jstring, jint, jboolean);
JNIEXPORT jint JNICALL Java_com_mam_lambo_AlgoWrapper_initLane(JNIEnv *, jobject, jint jImageWidth, jint jImageHeight);
JNIEXPORT jint JNICALL Java_com_mam_lambo_AlgoWrapper_initTailgating(JNIEnv* env, jobject that, jint jImageWidth, jint jImageHeight, jint jBufferLength);
JNIEXPORT jfloatArray JNICALL Java_com_mam_lambo_AlgoWrapper_execute(JNIEnv* env, jobject that, jobject jYBuffer, jobject jUBuffer, jobject jVBuffer, jint index);
JNIEXPORT void JNICALL Java_com_mam_lambo_AlgoWrapper_setFiducials(JNIEnv* jenv, jobject that, jfloatArray jinput);
JNIEXPORT jfloat JNICALL Java_com_mam_lambo_AlgoWrapper_executeTailgating(JNIEnv* jenv, jobject that, jfloatArray jBoxes, jint jBoxOffet, jint numberOfBoxes, jfloat jspeed, jlong jnow);
JNIEXPORT jint JNICALL Java_com_mam_lambo_AlgoWrapper_setKappa(JNIEnv* env, jobject that, jfloat kappa);
JNIEXPORT jint JNICALL Java_com_mam_lambo_AlgoWrapper_setPosThreshold(JNIEnv* env, jobject that, jint jPosThreshold);
JNIEXPORT jfloat JNICALL Java_com_mam_lambo_AlgoWrapper_getKappa(JNIEnv* env, jobject that);
JNIEXPORT jfloat JNICALL Java_com_mam_lambo_AlgoWrapper_getPosThreshold(JNIEnv* env, jobject that);
JNIEXPORT jint JNICALL Java_com_mam_lambo_AlgoWrapper_initializeCameraUnwarping(JNIEnv* env, jobject that, jint cameraIndex, jint resolution);
JNIEXPORT jdoubleArray JNICALL Java_com_mam_lambo_AlgoWrapper_getCameraUnwarping(JNIEnv* env, jobject that, jint cameraIndex);
JNIEXPORT jint JNICALL Java_com_mam_lambo_AlgoWrapper_unwarpImage(JNIEnv* env, jobject that, jint cameraIndex, jobject jYBuffer);
#ifdef __cplusplus
}
#endif
#endif
